language: php

php:
  - 5.5

branches:
  except:
    - /^bugfix\/.*$/
    - /^feature\/.*$/

cache:
  directories:
  - $TRAVIS_BUILD_DIR/vendor
  - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update && composer --version

install:
  - travis_retry composer update --no-interaction --prefer-source

before_script:

script:
  - ./vendor/bin/phpunit -c phpunit.xml
  # ./vendor/bin/phpmd ./src text ruleset.xml

after_script:
  - ./vendor/bin/coveralls -c .coveralls.yml -v

